export const PATH = {
    HOME: '/',
    REGISTER: '/register',
    LOGIN: '/login',
    REGISTER_COURSE: '/course/:id',
    REGISTER_CONFIRM: '/register/confirm',
    DETAIL_COURSE: '/users/course',
    PROFILE: '/profile',
    ADMIN_LOGIN: '/system/login',
    NOT_FOUND: '*',
    FORBIDEN: '/forbiden',
    SYSTEM: '/system',
    ADMIN_INFOR: '/system/user/:id',
    CALENDAR: '/system/users',
    FILE: '/system/classes',
    ADD_CLASS: '/system/class/add',
    USER_BY_CLASS: '/system/user-of-class/:id',
    EDIT_CLASS: '/system/class/edit/:id',
    REMIND: '/system/registers',
    ADD_USER: '/system/users/add',
    EDIT_USER: '/system/edit/user/:id',
    MANAGE_TIME: '/system/manage-time'
};
